#!/usr/bin/python

import os
import socket
from os import environ

home = os.getenv("HOME")

print "Location of home folder: ", home

hostname = socket.gethostname()

print "Hostname: ", hostname

print"Current shell: ", environ['SHELL']

directory = os.getcwd()

print "Current working directory: ", directory
